version: "3.9"

services:
  nova-api-gateway:
    build:
      context: .
      dockerfile: DOCKERFILE
    container_name: nova-api-gateway
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000
      LOG_LEVEL: info
      COOKIE_SECRET: change-me-in-production
      AUTH_SERVICE_URL: http://host.docker.internal:3001
      USER_SERVICE_URL: http://host.docker.internal:3002
      PRODUCT_SERVICE_URL: http://host.docker.internal:3003
      STORE_SERVICE_URL: http://host.docker.internal:3004
      ORDER_SERVICE_URL: http://host.docker.internal:3005
      PAYMENT_SERVICE_URL: http://host.docker.internal:3006
      DELIVERY_SERVICE_URL: http://host.docker.internal:3007
      ADMIN_SERVICE_URL: http://host.docker.internal:3008
      NOTIFICATION_SERVICE_URL: http://host.docker.internal:3009
      CLIENT_FRONTEND_URL: http://localhost:5173
      SELLER_FRONTEND_URL: http://localhost:5174
      ADMIN_FRONTEND_URL: http://localhost:5175
    extra_hosts:
      - "host.docker.internal:host-gateway"
